module:
  hugoVersion:
    min: "0.111.3"
    extended: true
  mounts:
  # Default mounts
  - source: "archetypes"
    target: "archetypes"
  - source: "assets"
    target: "assets"
  - source: "content"
    target: "content"
  - source: "data"
    target: "data"
  - source: "i18n"
    target: "i18n"
  - source: "layouts"
    target: "layouts"
  - source: "static"
    target: "static"
  # Bootstrap
  - source: "paige/node_modules/bootstrap/dist/css"
    target: "assets/css/paige/bootstrap"
    includeFiles: ["/bootstrap.css"]
  - source: "paige/node_modules/bootstrap/dist/js"
    target: "assets/js/paige/bootstrap"
    includeFiles: ["/bootstrap.bundle.js"]
  - source: "paige/node_modules/bootstrap/js/dist"
    target: "assets/js/paige/bootstrap"
  - source: "paige/node_modules/bootstrap/scss"
    target: "assets/css/paige/bootstrap"
  # Bootstrap Icons
  - source: "paige/node_modules/bootstrap-icons/font/fonts"
    target: "static/css/paige/bootstrap-icons/fonts"
  - source: "paige/node_modules/bootstrap-icons/font"
    target: "assets/css/paige/bootstrap-icons"
    includeFiles: ["/bootstrap-icons.css"]
  # Katex
  - source: "paige/node_modules/katex/dist/contrib"
    target: "assets/js/paige/katex"
    includeFiles: ["/auto-render.min.js"]
  - source: "paige/node_modules/katex/dist/fonts"
    target: "static/css/paige/katex/fonts"
  - source: "paige/node_modules/katex/dist"
    target: "assets/css/paige/katex"
    includeFiles: ["/katex.min.css"]
  - source: "paige/node_modules/katex/dist"
    target: "assets/js/paige/katex"
    includeFiles: ["/katex.min.js"]
