demosite = "https://willfaught.com/paige"
description = "Powerful, pliable pixel perfection. An advanced Hugo theme."
features = [
  "accessibility",
  "analytics",
  "atom feed",
  "authors",
  "blog",
  "bootstrap",
  "categories",
  "code shortcode",
  "comments",
  "customizable",
  "dark color scheme",
  "email shortcode",
  "facebook sharing",
  "figure shortcode",
  "gallery shortcode",
  "header links",
  "icon shortcode",
  "image pixel densities",
  "image shortcode",
  "image size breakpoints",
  "image thumbnails",
  "landing page",
  "languages",
  "light color scheme",
  "math typesetting",
  "menu",
  "minimal design",
  "quote shortcode",
  "rss feed",
  "responsive",
  "right-to-left languages",
  "seo",
  "safari and firefox reader view support",
  "search",
  "sections",
  "series",
  "single column",
  "social links",
  "table of contents",
  "tags",
  "twitter sharing",
  "validated",
  "vimeo shortcode",
  "youtube shortcode",
]
homepage = "https://github.com/willfaught/paige"
license = "MIT"
licenselink = "https://github.com/willfaught/paige/blob/master/LICENSE"
name = "Paige"
tags = [
  "blog",
  "bootstrap",
  "contact",
  "dark",
  "dark mode",
  "gallery",
  "hero",
  "landing",
  "light",
  "minimal",
  "multilingual",
  "personal",
  "portfolio",
  "responsive",
]

[author]
homepage = "https://willfaught.com"
name = "Will Faught"
