baseurl: "http://localhost"
copyright: "© Will Faught"
enablerobotstxt: true
languagecode: "en-us"
languages:
  en:
    menu:
      main:
      - identifier: "home"
        name: "Home"
        url: "/"
        weight: 10
      - identifier: "content"
        name: "Content"
        url: "/content/"
        weight: 20
      - identifier: "layouts"
        name: "Layouts"
        url: "/layouts/"
        weight: 30
      - identifier: "shortcodes"
        name: "Shortcodes"
        url: "/shortcodes/"
        weight: 40
      - identifier: "configuration"
        name: "Configuration"
        url: "/configuration/"
        weight: 50
      - identifier: "categories"
        name: "Categories"
        url: "/categories/"
        weight: 60
      - identifier: "tags"
        name: "Tags"
        url: "/tags/"
        weight: 70
      - identifier: "search"
        name: "Search"
        url: "/search/"
        weight: 80
    weight: 10
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noclasses: false
  tableofcontents:
    endlevel: 6
    ordered: true
    startlevel: 2
outputs:
  home:
  - "html"
  - "json"
  - "rss"
paginate: 50
params:
  authors:
    will_faught:
      name: "Will Faught"
  paige:
    credit:
      link:
        hide: true
    list:
      authors:
        hide: true
      date:
        hide: true
      date_header:
        hide: true
      reading_time:
        hide: true
      summary:
        hide: true
      terms:
        hide: true
    main:
      metadata:
        authors:
          hide: true
        date:
          hide: true
        git:
          commit_url_prefix: "https://github.com/willfaught/paige/commit/"
        reading_time:
          hide: true
        terms:
          hide: true
      table_of_contents:
        hide: true
social:
  twitter: "username"
theme: "paige"
timezone: "America/Los_Angeles"
titlecasestyle: "Go"
