baseurl: https://example.com
copyright: © Michael Bluth
enablerobotstxt: true
languagecode: en-us
languages:
  en:
    menu:
      main:
      - identifier: home
        name: Home
        url: /
        weight: 10
      - identifier: about
        name: About
        url: /about/
        weight: 20
      - identifier: blog
        name: Blog
        url: /blog/
        weight: 30
      - identifier: categories
        name: Categories
        url: /categories/
        weight: 40
      - identifier: tags
        name: Tags
        url: /tags/
        weight: 50
      - identifier: search
        name: Search
        url: /search/
        weight: 60
    title: No Borders, No Limits
    weight: 1
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: vs
  tableofcontents:
    endlevel: 6
    ordered: true
    startlevel: 2
outputs:
  home:
  - html
  - json
  - rss
paginate: 50
params:
  paige:
    hide_theme_comment: true
    hide_theme_link: true
    social:
      discord:
        name: Discord
        icon: discord
        url: https://discord.com/users/example
      email:
        name: E-mail
        icon: envelope
        url: mailto:example@example.com
      facebook:
        name: Facebook
        icon: facebook
        url: https://facebook.com/example
      github:
        name: GitHub
        icon: github
        url: https://github.com/example
      instagram:
        name: Instagram
        icon: instagram
        url: https://instagram.com/example
      linkedin:
        name: LinkedIn
        icon: linkedin
        url: https://www.linkedin.com/in/example
      reddit:
        name: Reddit
        icon: reddit
        url: https://reddit.com/u/example
      twitch:
        name: Twitch
        icon: twitch
        url: https://www.twitch.tv/example
      twitter:
        name: Twitter
        icon: twitter
        url: https://twitter.com/example
      youtube:
        name: YouTube
        icon: youtube
        url: https://www.youtube.com/user/example
permalinks:
  blog: /blog/:year/:month/:day/:title/
social:
  twitter: example
theme: paige
timezone: America/Los_Angeles
titlecasestyle: Go
